### ISSUE TITLE
Want to know the name of a person who created PR

### ISSUE THREAD

**Issue by trknhr** [vvatanabe/gbch#3]
Hi. it's a very useful library. I'm going to use it in my team.

But for now it shows only the name of a person who merged the PR in the change log.

I think it's better to show the name of a person creating the PR because it becomes one of the motivation to create new feature/bugfix for developers.

Please consider it.

Thank you.

**Comment by vvatanabe** [comment]
Thanks for the feedback.

I also think that it is better, and `ghch` as this library's origin shows the PR's creator. I would like to be compatible with the origin as much as possible.

I accept your suggestion and change the specs that way.

**Comment by vvatanabe** [comment]
@1984weed Done! Published `v0.2.0`. Plz update `go get -u github.com/vvatanabe/gbch` or install from release page https://github.com/vvatanabe/gbch/releases/tag/v0.2.0 .
